import Script from "next/script";
import "./globals.css";
import { Inter } from "next/font/google";

// const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: "Zesan",
    // description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <head>
                <Script
                    src="https://kit.fontawesome.com/d63d7fa193.js"
                    crossorigin="anonymous"
                ></Script>
            </head>
            <body>{children}</body>
        </html>
    );
}
